### ISSUE TITLE
refer lang or other rememberable name instead of number

### ISSUE THREAD

**Issue by anantshri** [0x00-0x00/ShellPop#12]
Just my 2 cents:
The method number is the worst part of an awesome code. if instead of number user can input something recognizable like say language or extension like ps1 for powershell php aspx asp cmd etc that would be more useful and quick to remember and recall.

**Comment by 0x00-0x00** [comment]
Hello, thanks for your suggestion.

I understand the problem. But I can't think a way to implement that to be more easier than a single index number.

Help me understand a way to improve that:
If there is three types of powershell payloads. 
1. Powershell TCP 01
2. Powershell TCP 02
3. Powershell UDP 01

How would the program know which one to choose? I would have to type "p o w e r s h e l l t c p 0 1"  to choose the first option? That's a way more harder than just --list and choose a number

**Comment by anantshri** [comment]
Ah didn't thought about two payloads of same type. But assuming all types have one payload per language something like 
```
--method ps1 --tcp 
```
or 
```
--method ps1 --udp
```
might solve the problem

**Comment by 0x00-0x00** [comment]
Yes, if there was a unique payload for each language, that would be awesome and surely would be better to do your way.

But there is more than one payload for each language, I dont know any way to circumvent that.
Like, powershell has number 9 and 22 in reverse.
Perl has two types too.

I plan to develop more advanced attacks that might involve powershell directly, then a single payload for each language will limit the tool.

But your suggestion is very relevant, and I have wrote this down in my notes. 
In a future version I might add a flag to quickly generate the first payload option for that language type.

Do you have any thing else to add?

**Comment by anantshri** [comment]
At this point that was my concern. However as you described there are more complexities. I will have a look at all the payloads and will see if i can add more to the list. will raise seperate issues for those.

**Comment by 0x00-0x00** [comment]
Thanks, so I will close this issue and add your suggestion to my to-do list!

**Comment by capnspacehook** [comment]
Would it be possible to use a Python tab-completion module to allow for easy payload selection? Like divide each payload into reverse/bind, Lang, tcp/udp, then specifics on what is different. For example: selecting a reverse awk tcp payload:
```
--payload reverse/awk/tcp
```
What do you think of that?

**Comment by 0x00-0x00** [comment]
Excellent workaround. I will look into that ASAP.

**Comment by 0x00-0x00** [comment]
![image](https://user-images.githubusercontent.com/23364530/39721491-18e25f6c-5216-11e8-9fa2-c08f216ba67a.png)

Thanks, It seems it suits perfectly to our purpose. I will start developing the changes very soon.

I can't thank you guys enough for the good ideas!

**Comment by 0x00-0x00** [comment]
Hello. I am here to tell you guys that I have already made the changes, and this feature will be cumulative to the current option set we already have.

So it is possible to use --payload linux/ [TAB]  or just stick to the current --number with --reverse or --bind flags.
![image](https://user-images.githubusercontent.com/23364530/39729137-a6f51c8a-5230-11e8-9a31-83d3ce315f71.png)

**Comment by capnspacehook** [comment]
Sweet man! Dang that was fast!

**Comment by anantshri** [comment]
awesome work man.
